//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ Compatible
// This file is automatically generated by RisohEditor.
// main_res.rc

#define IDD_MAIN                            100

#define IDI_MAINICON                        100

#define IDS_APPNAME                         100
#define IDS_VERSIONSTRING                   101
#define IDS_NEUTRAL                         102
#define IDS_OPENFILTER                      103
#define IDS_RUNTITLE                        104
#define IDS_FAILTORUN                       105
#define IDS_USAGE                           106

#ifdef APSTUDIO_INVOKED
    #ifndef APSTUDIO_READONLY_SYMBOLS
        #define _APS_NO_MFC                 1
        #define _APS_NEXT_RESOURCE_VALUE    100
        #define _APS_NEXT_COMMAND_VALUE     100
        #define _APS_NEXT_CONTROL_VALUE     1000
        #define _APS_NEXT_SYMED_VALUE       300
    #endif
#endif
